chore(deps): bump docker library version
GoogleCloudPlatform/composer-local-dev pull request #57
Opened 2024-05-30 09:26 UTC by nbonnotte

Fix #55 following the release of `docker 7.1.0` solving https://github.com/docker/docker-py/issues/3256

2024-07-06 04:20 UTC, feelingsonice commented
Related: https://github.com/GoogleCloudPlatform/composer-local-dev/issues/61

2024-10-16 16:03 UTC, williambarretolopes approved these changes

2024-10-16 16:14 UTC, williambarretolopes requested changes
Will need also to add  "requests==2.31" to fix Related: https://github.com/GoogleCloudPlatform/composer-local-dev/issues/61

2024-12-18 09:27 UTC, ahidalgob commented
Fixed in https://github.com/GoogleCloudPlatform/composer-local-dev/pull/74

2024-12-18 09:27 UTC, closed without merging